photon/src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

photon/src/photon/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
import profiles.urls
import accounts.urls
from . import views

# Personalized admin site settings like title and header
admin.site.site_title = 'Photon Site Admin'
admin.site.site_header = 'Photon Administration'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('users/', include(profiles.urls)),
    path('admin/', admin.site.urls),
    path('', include(accounts.urls)),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

photon/src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

photon/src/templates/_brandname.html
Mitostream

photon/src/templates/_navbar.html
      <div class="mdl-layout__header-row">
      <!-- Navigation -->
      <nav class="mdl-navigation">
        <a class="mdl-button mdl-js-button" href="{% url 'home' %}" role="button">Home</a>
        <a class="mdl-button mdl-js-button" href="{% url 'about' %}" role="button">About</a>
      </nav>

  </div>

</header>

photon/src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">The future of money</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/wes.jpg' %}" alt="profile pic"></div>
        <p class="heavy text-center">Wes M</p>
        <h2>Founder</h2>
        <p>Mitostream aims to bring the disruptive network properties of blockchain to the masses. Send money accross borders quickly for a fraction of a cent. Facilitate low-cost payments between different currencies. Increase effeciency and decrease the cost of smaller transfers. Provide services for the underbanked.</p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Director of Business Operations</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">

    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">Wes M</p>
        <h2>Director of Engineering</h2>
        <p>Mitostream aims to bring the disruptive network properties of blockchain to the masses. Send money accross borders quickly for a fraction of a cent. Facilitate low-cost payments between different currencies. Increase effeciency and decrease the cost of smaller transfers. Provide services for the underbanked.</p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>Director of Legal & Compliance</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Business Operations Manager</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Advisors</h2>
        <p class="lead">some catchy line about our awesome advisors</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">Bobby Lee</p>
        <h2>Executive and Entrepreneur</h2>
        <p>Bobby Lee is the CEO of BTCChina, the world's current second largest bitcoin exchange as of 2014. Founded in 2011, it was China's first bitcoin exchange, and most of its customers are thought to be Chinese. Bobby Lee joined in 2013, after investing his own money and attracting other investors, and contributed to the growth of the company in terms of market share and also in workforce, BTCChina now has 20 employees, instead of 2 when Bobby Lee joined..</p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="{% static 'site/img/default_profile.png' %}" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Mitostream LLC.</strong><br>
            1 Hacker Way<br>
            Menlo Park, CA 94025<br>
            United States<br>
            <abbr>Phone:</abbr> +1 (414) 405-9760
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(37.448491, -122.180281);

     var mapOptions = {
          center: myLocation,
          zoom: 9
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

photon/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Mitostream">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Material.io (getmdl.io) CSS -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-orange.min.css" />



    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}

    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Logo -->
          {% block navbar-brand %}

            <img src="{% static 'site/img/logo.png' %}" alt="logo"> &nbsp
            <a class="mdl-layout-title" href="/" style="text-decoration: none">{% include "_brandname.html" %} </a>

          {% endblock %}
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <a class="mdl-navigation__link" href="{% url 'admin:index' %}" style="text-decoration: none">Admin</a>
                {% endif %}






        <!--    <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" /> -->
            <a class="mdl-navigation__link" href="{% url 'profiles:show_self' %}" style="text-decoration: none">{{ user.get_full_name|truncatechars:20 }}</a>

            <!-- Right aligned menu below button -->
            <button id="demo-menu-lower-right"
                    class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">more_vert</i>
            </button>

            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                for="demo-menu-lower-right">
              <li class="mdl-menu__item"><a href="{% url 'profiles:show_self' %}">Profile</a></li>
              <li class="mdl-menu__item"><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>


              {% endif %}
            {% endblock %}
          </nav>
        </div>
      </header>

      {% block navbar-menu %}
    <!--  <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
          <a class="mdl-navigation__link" href="">Link</a>
        </nav>
      </div>
    -->
      {% block navbar-left %}{% endblock %}

      <main class="mdl-layout__content">
        <div class="page-content"><!-- Your content goes here --></div>
      </main>
    </div>


    </ul>
    </ul>
    </div><!--/.nav-collapse -->
    {% endblock %}
    </div>
    {% endblock navbar %}








    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}

    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; {% include "_brandname.html" %}  {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Material.io (getmdl.io) JavaScript -->
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

photon/src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="mdl-navigation__link" href="{% url 'accounts:login' %}" style="text-decoration: none">Login</a>
<a class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent" href="{% url 'accounts:signup' %}" role="button">Sign up</a>

  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}


{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">

  </div>
{% endblock splash %}

{% block container %}


<!-- Benefits of the Django application -->




<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>

<!-- MailChimp JS signup model-->
<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script>
<script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us17.list-manage.com","uuid":"1a0969b09324a3540c0e2ee6d","lid":"1e14212914"}) })</script>
{% endblock scripts %}